FROM ubuntu:plucky

ENV TZ=UTC
LABEL maintainer="Pham Kieu Thanh <thanh@kieu.co>"

RUN set -eux; \
	apt-get update; \
	DEBIAN_FRONTEND=noninteractive apt-get full-upgrade -y; \
	DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
	squid ca-certificates tzdata apache2-utils wget; \
	DEBIAN_FRONTEND=noninteractive apt-get remove --purge --auto-remove -y; \
	rm -rf /var/lib/apt/lists/*; \
	# Change default configuration to allow local network access \
	sed -i 's/^#http_access allow localnet$/http_access allow localnet/' /etc/squid/conf.d/debian.conf; \
	echo "# Set max_filedescriptors to avoid using system's RLIMIT_NOFILE. See LP: #1978272" > /etc/squid/conf.d/rock.conf; \
	echo 'max_filedescriptors 1024' >> /etc/squid/conf.d/rock.conf; \
	# Remove the snakeoil self-signed certificate generated by the ssl-cert package
	rm -f /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/ssl/private/ssl-cert-snakeoil.key; \
	# smoketest
	/usr/sbin/squid --version; \
	# create manifest \
	mkdir -p /usr/share/rocks; \
	(echo "# os-release" && cat /etc/os-release && echo "# dpkg-query" && dpkg-query -f '${db:Status-Abbrev},${binary:Package},${Version},${source:Package},${Source:Version}\n' -W) > /usr/share/rocks/dpkg.query

# Download frpc
RUN wget https://github.com/fatedier/frp/releases/download/v0.58.1/frp_0.58.1_linux_amd64.tar.gz
RUN tar -xzvf ./frp_0.58.1_linux_amd64.tar.gz
RUN mv ./frp_0.58.1_linux_amd64/frpc ./
RUN rm ./frp_0.58.1_linux_amd64.tar.gz
RUN rm -R ./frp_0.58.1_linux_amd64

VOLUME /var/log/squid \
	/var/spool/squid

COPY squid.conf /etc/squid/squid.conf

COPY entrypoint.sh /usr/local/bin/entrypoint.sh
COPY frpc.toml ./frpc.toml
ENTRYPOINT ["entrypoint.sh"]

CMD ["-f", "/etc/squid/squid.conf", "-NYC"]
